name: geocomp
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - gdal
  - fiona  
  - rasterio
  - pip:
    - numpy
    - pandas
    - keplergl
    - geopandas
    - shapely
    - folium
    - pysal
    
    
    
